### PR TITLE
PROGRAMMES-6525 Avoiding entities promoting themselves

### PR DESCRIPTION
**Pull request by votemike**
You can test at http://sandbox.bbc.co.uk/programmes/b072hxhx?__flush_cache=1

### CODE REVIEW

**Comment by programmes-developers** [comment]
Can one of the admins verify this patch?

**Comment by benolot** [comment]
Do we not want that branch to be merged to dev rather than changing PPS to use a specific branch?

**Comment by votemike** [comment]
We do (as per this PRs description). But the branch isn't merged yet. Will update this PR when it is. But people can checkout this branch to test the other PR.

**Comment by programmes-developers** [comment]
Can one of the admins verify this patch?

**Pull request merged**
