### PR TITLE
Improved frontend performance

### PR DESCRIPTION
**Pull request by Tasiobg**
Bases on the frontend perforace traininig @votemike and my self did the other day we identify some improvements

Commits:
- Reorder headers to follow this optimal order: Char encoding, then Title tag, then inline scripts, then stylesheets, then inline style tags, then all JS, then meta tags (apart from viewport, charset and equiv)
- Added dns-prefetch

Those improvements decrase the amount of bloking times when loading a page, especially notizable by users who first visit our pages in a slow connection.

### CODE REVIEW

**Comment by programmes-developers** [comment]
Can one of the admins verify this patch?

**Comment by BjornTwachtmann** [comment]
Assuming stuff has just been moved around in the <head> I can't see this causing any major issues.

**Comment by BPScott** [comment]
Sounds like we'd want to do this in the base_amen template too?

**Comment by felipeparaujo** [comment]
As @BPScott said, should probably do that for amen pages. What sort of improvement are we seeing with these changes?

**Comment by BjornTwachtmann** [comment]
@felipeparaujo @BPScott , we created a ticket for that, https://jira.dev.bbc.co.uk/browse/PROGRAMMES-6267

**Pull request merged**
