### PR TITLE
feat(composer): Update branding-client version

### PR DESCRIPTION
**Pull request by bbc-kellys**
## Changes

- Updates the verison of `branding-client` to 4.1.0
- This adds the forge-free header for Orbit

## JIRA
https://jira.dev.bbc.co.uk/browse/DATCAP-80

### CODE REVIEW

**Review by gmarinov — CHANGES_REQUESTED** [review]
best to retarget just branding-client for now

**Comment by bbc-kellys** [comment]
> best to retarget just branding-client for now

when trying to update the branding-client specifically, I run into an error
`Your requirements could not be resolved to an installable set of packages.`
 I'm using composer.lock from master now, but can't seem to get it to update

**Review by murkas — APPROVED** [review]
Looks good to me!

**Review by Tasiobg — APPROVED** [review]
Not tested but looks good

**Review by gmarinov — APPROVED** [review]
what could go wrong

**Pull request merged**
