### PR TITLE
PROGRAMMES-5856 Using PHPStans memory limit option

### PR DESCRIPTION
**Pull request by votemike**
https://jira.dev.bbc.co.uk/browse/PROGRAMMES-5856

Very important that Jenkins runs the tests on this branch as there were problems before.

### CODE REVIEW

**Comment by votemike** [comment]
Test this please

**Comment by votemike** [comment]
Test me please.

**Comment by programmes-developers** [comment]
Can one of the admins verify this patch?

**Comment by votemike** [comment]
Test this please

**Comment by programmes-developers** [comment]
Can one of the admins verify this patch?

**Pull request merged**
