### PR TITLE
PROGRAMMES-6465 Update all HTTP APIs to use the Multi client 

### PR DESCRIPTION
**Pull request by Tasiobg**
- Updated Recommendations API to use Multi client

I'll open more PRs for the remaining tasks

### CODE REVIEW

**Comment by programmes-developers** [comment]
Can one of the admins verify this patch?

**Comment by votemike** [comment]
Do tests not need to be updated?

**Comment by Tasiobg** [comment]
@votemike current tests looks fine to me but let me know if you think there is anything I shold change

**Comment by votemike** [comment]
It just seems odd that you can make these changes without tests breaking. Maybe it means the files aren't tested enough.

**Comment by programmes-developers** [comment]
Can one of the admins verify this patch?

**Pull request merged**
