### PR TITLE
PROGRAMMES-6207 general heading cleanup

### PR DESCRIPTION
**Pull request by votemike**
Part of the work for https://jira.dev.bbc.co.uk/browse/PROGRAMMES-6207

Couldn't find an example of templates/partial/on_now_legacy_2013.html.twig to test. But tested the other two and they look OK.

### CODE REVIEW

**Comment by programmes-developers** [comment]
Can one of the admins verify this patch?

**Comment by votemike** [comment]
Me or the testers? How does one do that locally?

**Comment by BjornTwachtmann** [comment]
You can do that locally by firing up the PAL sandbox, I *think* it should request things from sandbox.bbc.co.uk for the on-now partial in the footer, but check it. You can also just deploy the branch somewhere. Or make the testers do it. Just make sure it's done :)

**Comment by votemike** [comment]
Test this please

**Comment by votemike** [comment]
Seems to work on INT.

**Comment by votemike** [comment]
Test this please

**Pull request merged**
