### PR TITLE
PROGRAMMES-6092 Fixing localisation bug

### PR DESCRIPTION
**Pull request by votemike**
https://jira.dev.bbc.co.uk/browse/PROGRAMMES-6092

### CODE REVIEW

**Comment by programmes-developers** [comment]
Can one of the admins verify this patch?

**Comment by Tasiobg** [comment]
Seems working fine, do you know why `local_date_intl()` return a wrong year?

**Comment by programmes-developers** [comment]
Can one of the admins verify this patch?

**Comment by votemike** [comment]
Because it's a date, like 2011-01-01 00:00:00 and then locally it was making it 2010-12-31 23:00:00

**Pull request merged**
