### PR TITLE
PROGRAMMES-5875 Fixing spacing

### PR DESCRIPTION
**Pull request by votemike**
Bodge to fixing magic empty div that exists in live.
https://jira.dev.bbc.co.uk/browse/PROGRAMMES-5875

### CODE REVIEW

**Comment by programmes-developers** [comment]
Can one of the admins verify this patch?

**Comment by BjornTwachtmann** [comment]
I'm assuming this is what the existing page does?

**Comment by votemike** [comment]
Yeah. There's some mystery empty div.

**Comment by BjornTwachtmann** [comment]
Fair enough. Merge it then I guess.

**Comment by BPScott** [comment]
Of those classes, programmes-page is the only one that provides any vertical padding. It should probably be applied to a wrapping div instead though.

**Comment by votemike** [comment]
@BPScott The gap isn't as big if I put it on the wrapping div... Is that OK?

**Pull request merged**
