### PR TITLE
Fixing bug with timezones

### PR DESCRIPTION
**Pull request by votemike**
https://jira.dev.bbc.co.uk/browse/PROGRAMMES-5707

### CODE REVIEW

**Comment by programmes-developers** [comment]
Can one of the admins verify this patch?

**Comment by BPScott** [comment]
Nice. Should we have a controller test that checks the messages on these start/end days?

**Comment by votemike** [comment]
That would mean testing the view. Right? How does one test the view?

**Comment by votemike** [comment]
Added tests

**Pull request merged**
