### PR TITLE
Add missing CSS class to standalone cta

### PR DESCRIPTION
**Pull request by felipeparaujo**

### CODE REVIEW

**Comment by programmes-developers** [comment]
Can one of the admins verify this patch?

**Comment by felipeparaujo** [comment]
please test this

**Comment by felipeparaujo** [comment]
test this please

**Comment by felipeparaujo** [comment]
test this please

**Comment by votemike** [comment]
Does this fix this ticket? https://jira.dev.bbc.co.uk/browse/PROGRAMMES-6012

**Comment by felipeparaujo** [comment]
@votemike It's not for that, but it looks like it's not broken anymore...

**Pull request merged**
