### PR TITLE
Timezone malarkey

### PR DESCRIPTION
**Pull request by BjornTwachtmann**
Make schedules page and presentation layer in general respect "local" time

### CODE REVIEW

**Comment by programmes-developers** [comment]
Can one of the admins verify this patch?

**Comment by BjornTwachtmann** [comment]
See also https://github.com/bbc/programmes-pages-service/pull/123

**Comment by felipeparaujo** [comment]
besides making a lot of tests fail, this looks fine

**Comment by BjornTwachtmann** [comment]
If you switch to the relevant pages service branch the tests should pass

**Pull request merged**
