### PR TITLE
restore change. Tx column css height issue

### PR DESCRIPTION
**Pull request by tatitati**
I did a fix that was looking good, but today I saw that still some ede cases were failing. I prefer to restore everything (if I go for holidays this will make clearer that still has not been fixed).

Original PR:
https://github.com/bbc/programmes-frontend/pull/512

### CODE REVIEW

**Comment by programmes-developers** [comment]
Can one of the admins verify this patch?

**Comment by votemike** [comment]
Have you marked the ticket as not fixed?
Which PR was this from?

**Comment by BjornTwachtmann** [comment]
what's failing here @tatitati , reverting it seems weird

**Comment by votemike** [comment]
What is a fauxcolumn anyway?

**Comment by tatitati** [comment]
After the "fix" the height of the columns were correct, but when you reduce the width happen this:

## Without fauxcolumn
withou-fauxcolumn



## With:
withfauxcolumn

**Pull request merged**
